name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - index.js
      - yarn.lock
  pull_request:
    branches: [ "main" ]
    paths:
      - index.js
      - yarn.lock

jobs:
  test:
    if: "!startsWith(github.event.head_commit.message, '[RELEASE] ')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build using ncc
        run: |
          yarn ncc build main.js -o dist/main
          yarn ncc build post.js -o dist/post
      - name: Run action
        uses: ./
        with:
          access-token: 'token'
          firewall-id: 'id'
          dry-run: true
